[2023-08-25T10:45:04.761+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: jinja_sql_dag.create_table_task manual__2023-08-25T10:45:03.472418+00:00 [queued]>
[2023-08-25T10:45:04.767+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: jinja_sql_dag.create_table_task manual__2023-08-25T10:45:03.472418+00:00 [queued]>
[2023-08-25T10:45:04.767+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-08-25T10:45:04.774+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_table_task> on 2023-08-25 10:45:03.472418+00:00
[2023-08-25T10:45:04.778+0000] {standard_task_runner.py:57} INFO - Started process 403 to run task
[2023-08-25T10:45:04.782+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'jinja_sql_dag', 'create_table_task', 'manual__2023-08-25T10:45:03.472418+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/6_jinja/jinja_dev.py', '--cfg-path', '/tmp/tmpfoinrttv']
[2023-08-25T10:45:04.783+0000] {standard_task_runner.py:85} INFO - Job 53: Subtask create_table_task
[2023-08-25T10:45:04.824+0000] {task_command.py:415} INFO - Running <TaskInstance: jinja_sql_dag.create_table_task manual__2023-08-25T10:45:03.472418+00:00 [running]> on host 83fdf19a2df8
[2023-08-25T10:45:04.876+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='jinja_sql_dag' AIRFLOW_CTX_TASK_ID='create_table_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-25T10:45:03.472418+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-25T10:45:03.472418+00:00'
[2023-08-25T10:45:04.877+0000] {sql.py:274} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS final_destination (
            rank_game INTEGER,
            name_game TEXT,
            platform TEXT,
            year_game INTEGER,
            genre_game TEXT,
            publisher TEXT,
            na_sales FLOAT,
            eu_sales FLOAT,
            jp_sales FLOAT,
            other_sales FLOAT,
            global_sales FLOAT,
            load_date DATE
        );
    
[2023-08-25T10:45:04.885+0000] {base.py:73} INFO - Using connection ID 'postgresql_connection' for task execution.
[2023-08-25T10:45:04.895+0000] {base.py:73} INFO - Using connection ID 'postgresql_connection' for task execution.
[2023-08-25T10:45:04.903+0000] {sql.py:418} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS final_destination (
            rank_game INTEGER,
            name_game TEXT,
            platform TEXT,
            year_game INTEGER,
            genre_game TEXT,
            publisher TEXT,
            na_sales FLOAT,
            eu_sales FLOAT,
            jp_sales FLOAT,
            other_sales FLOAT,
            global_sales FLOAT,
            load_date DATE
        );
    , parameters: None
[2023-08-25T10:45:04.918+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(final_destination, 2200) already exists.

[2023-08-25T10:45:04.926+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=jinja_sql_dag, task_id=create_table_task, execution_date=20230825T104503, start_date=20230825T104504, end_date=20230825T104504
[2023-08-25T10:45:04.933+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 53 for task create_table_task (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(final_destination, 2200) already exists.
; 403)
[2023-08-25T10:45:04.953+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-25T10:45:04.970+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
