[2023-08-24T03:07:00.238+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT_analytics_video_games.clean_destination_postgresql manual__2023-08-24T03:06:57.633684+00:00 [queued]>
[2023-08-24T03:07:00.243+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT_analytics_video_games.clean_destination_postgresql manual__2023-08-24T03:06:57.633684+00:00 [queued]>
[2023-08-24T03:07:00.244+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-08-24T03:07:00.250+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): clean_destination_postgresql> on 2023-08-24 03:06:57.633684+00:00
[2023-08-24T03:07:00.254+0000] {standard_task_runner.py:57} INFO - Started process 86 to run task
[2023-08-24T03:07:00.258+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ELT_analytics_video_games', 'clean_destination_postgresql', 'manual__2023-08-24T03:06:57.633684+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/3_ETL_mysql_postgresql_dag/ELT_dag.py', '--cfg-path', '/tmp/tmpyok6kl9h']
[2023-08-24T03:07:00.261+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask clean_destination_postgresql
[2023-08-24T03:07:00.303+0000] {task_command.py:415} INFO - Running <TaskInstance: ELT_analytics_video_games.clean_destination_postgresql manual__2023-08-24T03:06:57.633684+00:00 [running]> on host e8580f1cc731
[2023-08-24T03:07:00.356+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Willis' AIRFLOW_CTX_DAG_ID='ELT_analytics_video_games' AIRFLOW_CTX_TASK_ID='clean_destination_postgresql' AIRFLOW_CTX_EXECUTION_DATE='2023-08-24T03:06:57.633684+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-24T03:06:57.633684+00:00'
[2023-08-24T03:07:00.358+0000] {sql.py:274} INFO - Executing:  TRUNCATE TABLE sales;
[2023-08-24T03:07:00.374+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 275, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 186, in get_db_hook
    return self._hook
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 148, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgresql_connection` isn't defined
[2023-08-24T03:07:00.377+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=ELT_analytics_video_games, task_id=clean_destination_postgresql, execution_date=20230824T030657, start_date=20230824T030700, end_date=20230824T030700
[2023-08-24T03:07:00.384+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task clean_destination_postgresql (The conn_id `postgresql_connection` isn't defined; 86)
[2023-08-24T03:07:00.432+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-24T03:07:00.450+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
