[2023-08-25T10:59:46.085+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: jinja_sql_dag.incremental_insert_task manual__2023-08-25T10:59:44.363891+00:00 [queued]>
[2023-08-25T10:59:46.090+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: jinja_sql_dag.incremental_insert_task manual__2023-08-25T10:59:44.363891+00:00 [queued]>
[2023-08-25T10:59:46.091+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-08-25T10:59:46.097+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): incremental_insert_task> on 2023-08-25 10:59:44.363891+00:00
[2023-08-25T10:59:46.101+0000] {standard_task_runner.py:57} INFO - Started process 652 to run task
[2023-08-25T10:59:46.104+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'jinja_sql_dag', 'incremental_insert_task', 'manual__2023-08-25T10:59:44.363891+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/6_jinja/jinja_dev.py', '--cfg-path', '/tmp/tmp9t3vd9l1']
[2023-08-25T10:59:46.106+0000] {standard_task_runner.py:85} INFO - Job 63: Subtask incremental_insert_task
[2023-08-25T10:59:46.144+0000] {task_command.py:415} INFO - Running <TaskInstance: jinja_sql_dag.incremental_insert_task manual__2023-08-25T10:59:44.363891+00:00 [running]> on host 83fdf19a2df8
[2023-08-25T10:59:46.194+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='jinja_sql_dag' AIRFLOW_CTX_TASK_ID='incremental_insert_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-25T10:59:44.363891+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-25T10:59:44.363891+00:00'
[2023-08-25T10:59:46.195+0000] {sql.py:274} INFO - Executing: 
        INSERT INTO final_destination
        SELECT * FROM public.sales
        WHERE load_date between '2024-01-01' and '2024-01-03'
        ON CONFLICT (rank_game, load_date) DO NOTHING;
    
[2023-08-25T10:59:46.205+0000] {base.py:73} INFO - Using connection ID 'postgresql_connection' for task execution.
[2023-08-25T10:59:46.214+0000] {base.py:73} INFO - Using connection ID 'postgresql_connection' for task execution.
[2023-08-25T10:59:46.221+0000] {sql.py:418} INFO - Running statement: 
        INSERT INTO final_destination
        SELECT * FROM public.sales
        WHERE load_date between '2024-01-01' and '2024-01-03'
        ON CONFLICT (rank_game, load_date) DO NOTHING;
    , parameters: None
[2023-08-25T10:59:46.224+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InvalidColumnReference: there is no unique or exclusion constraint matching the ON CONFLICT specification

[2023-08-25T10:59:46.233+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=jinja_sql_dag, task_id=incremental_insert_task, execution_date=20230825T105944, start_date=20230825T105946, end_date=20230825T105946
[2023-08-25T10:59:46.239+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 63 for task incremental_insert_task (there is no unique or exclusion constraint matching the ON CONFLICT specification
; 652)
[2023-08-25T10:59:46.276+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-25T10:59:46.294+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
